### ISSUE TITLE
Allow me to customize the target table

### ISSUE THREAD

**Issue by kevinmic** [patka/cassandra-migration#11]
I have a need where I want to run only certain migrations in a given environment.     The way I got around this problem in the past was simply to have 2 different version tables (schema_migrations, schema_migrations_v2)
This still seems like the easiest path forward.   Thoughts?

**Comment by kevinmic** [comment]
If your open to it, I have linked my pull request.
#12

**Comment by patka** [comment]
Hi,

while it is certainly possible to allow the name of the migration table to be customized, I will would like to understand your need a little bit more.

Normally, the whole idea is that the schema of the database is versioned by the application using it. The only scenario I can think of where you might not want to have one application always upgrading to its latest stage is when you access the same database from two or more applications at the same time. Normally this is something you should try to avoid if possible because it leads to the problem that one application upgrades the schema and therefore breaks another.

Based on this, I would assume that your goal might be to not update to the latest version but a version somewhere in between, is this correct? In that case would it not help you more to have a way to specify the version to which you want to upgrade. So basically you can specify in the migration task to which version it upgrades even if there are more versions available in the code?

Cheers
Patrick

**Comment by kevinmic** [comment]
No, what I am really trying to do is have environment specific migrations.    For me I have multiple environments (developer/QA/production).   There are certain updates (non DDL) that I only want processed in certain environments.  For example I have initialization scripts that I only want run on a developers machine.   Or in production I want to update/fix information for a specific account but that account only exist in production.

What I was accomplishing by being able to specify the migration table was the ability to have 2 migration tables for a single environment.   It was a hack to try and achieve what I described above.   Maybe there is a better way to get what I am looking for?
