### ISSUE TITLE
Support comments that don't start at the beginning of the line

### ISSUE THREAD

**Issue by georgeck** [patka/cassandra-migration#19]
Currently the code that does `isLineComment()` uses the following regex to parse line comments:
https://github.com/patka/cassandra-migration/blob/2ca11b3c9badd15e04129a40d35007a39cec853e/cassandra-migration/src/main/java/org/cognitor/cassandra/migration/MigrationRepository.java#L67

This regex will support line comments that start at the beginning of the line but will fail for comments like below.
```
CREATE TABLE users (
  // Some comment that does not start a the beginning of the line
  userid text PRIMARY KEY,
// This comment start at the beginning of the line and is supported
  first_name text,
 );
```
Can we change the regex to this: `"(^\s*--.*)|(^\s*//.*)"` to support CQL files like above?

**Comment by patka** [comment]
Hi,

yes we can change it but I want to evaluate first if it collides with Issue #17. I think if we store the checksum it might make sense to store the script with the comments in the database. Currently with the pattern, the comments are ignored. I might change it now as it is consistent with the default behavior and have a version 3 later that will include the checksum as well as some other feature requests that might change a little bit how thinks work.

Cheers
Patrick

**Comment by patka** [comment]
Hi,

I just worked on this issue. While the pattern was working fine it is actually no longer required as the Database is now using the SimpleCQLLexer that knows how to filter out the comments.
However, I will include this in version 3 as this means that the comments are also stored inside the schema migration table which is not the case at the moment. Since version 3 will also introduce the checksum feature, I will anyway need to introduce a way to update the migration table without actually executing the migrations again and it would be a good fit to do the comments there as well.
Sorry, it took so long but it will come.

Cheers
Patrick

**Comment by patka** [comment]
Fixed with commit https://github.com/patka/cassandra-migration/commit/773fad1f4e375e4e2118c10192df840813fa2e16
